Add React template
DevExpress-Examples/DevExtreme-Examples-Template pull request #2
Opened 2021-02-19 14:27 UTC by artem-kurchenko

- A simple template with DevExtreme button and  Material Compact Theme
- All unnecessary styles are removed
- Strict Mode removed from index.js
- Readme.md updated to match the default pattern we have in the current examples

2021-02-19 15:36 UTC, LexDX requested changes
We need to get rid of yarn.lock. The farm just does not use yarn. Also, maybe we can remove basic comments.

2021-02-19 15:36 UTC, LexDX commented on React/package.json
> +    "react": "^17.0.1",
It is necessary to downgrade to 16, for now, bcs of the bug in our React integration. Also, a peer-dep error may occur

2021-02-19 15:36 UTC, LexDX commented on React/public/index.html
> +  <body>
dx-viewport ?

2021-02-19 15:36 UTC, LexDX commented on React/public/index.html
> +      manifest.json provides metadata used when your web app is installed on a
I think we can remove all these comments

2021-02-19 15:36 UTC, LexDX commented on React/src/App.css
> +.App {
Do we really need anything there?

2021-02-20 08:11 UTC, artem-kurchenko commented on React/src/App.css
> +.App {
yep

2021-02-20 08:15 UTC, merged

2021-02-20 08:26 UTC, LexDX reviewed
lgtm